### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by bparrish0** [HubbleCommand/GTARadio#2]
I've been interested in a project like this and couldn't find much last time I looked. Really want to try out the PI version of this. You mentioned to email you to get a link for the audio but I don't see your email address anywhere. That sure would save a lot of time over ripping it from the game. Can you still provide that? My email is brandon@ipherring.com.

**Comment by HubbleCommand** [comment]
Sent the email, you might need to check your spam.

I don't recommend doing this on Arduino as finding good audio amp chips is a pain.

While I used PyGame for the python / pi version, I find it doesn't scale well for larger projects and use Qt (there's PyQt and PySide if you want to still use Python instead of C++, the only real difference between the two is GPL vs LGPL).

**Comment by bparrish0** [comment]
I really appreciate it but I don’t see the email in spam or anywhere. Could you please send it to Parrish.Brandon@gmail.com. Thanks!

**Comment by HubbleCommand** [comment]
https://mab.to/v06Fi5AwE
